version: "3.9"
services:
  card-generation-service:
    build: .
    container_name: card-generation-service
    env_file:
      - .env
    environment:
      MONGO_DB_CONNECTION: "mongodb://mongodb:27017"
      MODEL_PATH: "/Users/moritzeich/dev/spacey/card-generation-service/distilbert-base-cased-distilled-squad"
    volumes:
      - /Users/moritzeich/dev/spacey/card-generation-service/distilbert-base-cased-distilled-squad:/Users/moritzeich/dev/spacey/card-generation-service/distilbert-base-cased-distilled-squad
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT} --log-level ${LOG_LEVEL} --workers 1 --reload
    ports:
      - "3333:${PORT}"
    networks:
      - spacey-services

networks:
  spacey-services:
    name: spacey-services
    driver: bridge
