version: "3.9"
services:
  card-generation-service:
    build: ./
    container_name: card-generation-service
    env_file:
      - .env
    environment:
      MONGO_DB_CONNECTION: "mongodb://mongodb:27017"
    networks:
      - spacey-services

networks:
  spacey-services:
    name: spacey-services
    driver: bridge
