name: Run Tests

on:
    pull_request:
        branches: [master, staging]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.11.x"
            - name: Setup Poetry
              run: |
                  pip install "poetry==1.5.0"
                  poetry config virtualenvs.create false
                  poetry install
            #- name: Run mypy
            #  python -m mypy .
            - name: Run tests
              run: python -m pytest
